networks:
  sqlx-rust:
    driver: bridge

volumes:
  pgdata:

services:
  postgres:
    image: postgres:latest
    container_name: sqlx_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5433}:5432"  # 6432 o'rniga 5433
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sqlx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-sqlx_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sqlx-rust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sqlx_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer:latest
    container_name: sqlx_adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-3000}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sqlx-rust
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"
